version: "3.9"
services:
  db: 
    image: mysql
    container_name: mysql-test
    ports:
      - "4000:4000"
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
    volumes:
      - ./query:/user/src/mysql/query
