version: "3.9"
services:
  db:
    image: 
      mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - "5000:3306"
    command:
      --default-authentication-plugin=mysql_native_password
  app:
    image: 
      node
    volumes:
      - ./:/app
    working_dir:
      /app
    command: 
      bash -c "npm install && node app.js"
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1111"
    depends_on:
      - db